import os
import logging
from dataclasses import dataclass

import cascadio

logger = logging.getLogger(__name__)


@dataclass
class ConversionResult:
    obj_path: str
    file_size_bytes: int
    vertex_count: int
    face_count: int
    engine: str


def _count_obj_geometry(obj_path: str) -> tuple[int, int]:
    """Parse an OBJ file and return (vertex_count, face_count)."""
    vertices = 0
    faces = 0
    with open(obj_path, "r", encoding="utf-8", errors="replace") as f:
        for line in f:
            stripped = line.strip()
            if stripped.startswith("v "):
                vertices += 1
            elif stripped.startswith("f "):
                faces += 1
    return vertices, faces


def _convert_cascadio(
    step_path: str,
    obj_path: str,
    linear_tolerance: float = 0.001,
    angular_tolerance: float = 0.5,
) -> None:
    """Tessellate using cascadio (OpenCASCADE BRepMesh)."""
    step_posix = step_path.replace("\\", "/")
    obj_posix = obj_path.replace("\\", "/")
    cascadio.step_to_obj(
        step_posix,
        obj_posix,
        tol_linear=linear_tolerance,
        tol_angular=angular_tolerance,
    )


def _convert_gmsh(
    step_path: str,
    obj_path: str,
    mesh_size_factor: float = 1.0,
) -> None:
    """Tessellate using GMSH's meshing engine (Delaunay-based)."""
    import gmsh

    gmsh.initialize()
    try:
        gmsh.option.setNumber("General.Terminal", 0)
        gmsh.model.occ.importShapes(step_path.replace("\\", "/"))
        gmsh.model.occ.synchronize()

        bb = gmsh.model.getBoundingBox(-1, -1)
        diag = ((bb[3]-bb[0])**2 + (bb[4]-bb[1])**2 + (bb[5]-bb[2])**2) ** 0.5
        target_size = diag * 0.02 * mesh_size_factor

        gmsh.option.setNumber("Mesh.CharacteristicLengthMin", target_size * 0.1)
        gmsh.option.setNumber("Mesh.CharacteristicLengthMax", target_size)
        gmsh.option.setNumber("Mesh.Algorithm", 6)  # Frontal-Delaunay

        gmsh.model.mesh.generate(2)

        node_tags, coords, _ = gmsh.model.mesh.getNodes()
        tag_to_idx = {}
        vertices = []
        for i, tag in enumerate(node_tags):
            tag_to_idx[tag] = i + 1
            vertices.append(coords[3*i : 3*i + 3])

        faces = []
        element_types, element_tags, node_tags_per_elem = gmsh.model.mesh.getElements(2)
        for et, ntags in zip(element_types, node_tags_per_elem):
            name, dim, order, num_nodes, _, _ = gmsh.model.mesh.getElementProperties(et)
            if dim != 2:
                continue
            for j in range(0, len(ntags), num_nodes):
                face_nodes = ntags[j : j + num_nodes]
                if num_nodes == 3:
                    faces.append([tag_to_idx[n] for n in face_nodes])
                elif num_nodes == 4:
                    idxs = [tag_to_idx[n] for n in face_nodes]
                    faces.append([idxs[0], idxs[1], idxs[2]])
                    faces.append([idxs[0], idxs[2], idxs[3]])
    finally:
        gmsh.finalize()

    with open(obj_path, "w", encoding="utf-8") as f:
        f.write("# Generated by GMSH engine\n")
        for v in vertices:
            f.write(f"v {v[0]:.8f} {v[1]:.8f} {v[2]:.8f}\n")
        for face in faces:
            f.write("f " + " ".join(str(i) for i in face) + "\n")


ENGINES = {
    "opencascade": _convert_cascadio,
    "gmsh": _convert_gmsh,
}


def convert_step_to_obj(
    step_path: str,
    obj_path: str,
    engine: str = "opencascade",
) -> ConversionResult:
    """
    Convert a STEP file to OBJ using the specified tessellation engine.

    Supported engines: "opencascade" (cascadio), "gmsh".
    Raises ValueError for bad input, RuntimeError for conversion failures.
    """
    if not os.path.isfile(step_path):
        raise FileNotFoundError(f"STEP file not found: {step_path}")

    ext = os.path.splitext(step_path)[1].lower()
    if ext not in (".step", ".stp"):
        raise ValueError(f"Unsupported file extension '{ext}'. Expected .step or .stp")

    if engine not in ENGINES:
        raise ValueError(f"Unknown engine '{engine}'. Choose from: {list(ENGINES.keys())}")

    logger.info("Converting STEP -> OBJ [engine=%s]: %s", engine, step_path)
    try:
        ENGINES[engine](step_path, obj_path)
    except Exception as exc:
        raise RuntimeError(f"Conversion failed ({engine}): {exc}") from exc

    if not os.path.isfile(obj_path):
        raise RuntimeError("OBJ file was not created — conversion may have failed silently")

    file_size = os.path.getsize(obj_path)
    vertex_count, face_count = _count_obj_geometry(obj_path)

    logger.info(
        "Conversion complete [%s]: %d vertices, %d faces, %.1f KB",
        engine,
        vertex_count,
        face_count,
        file_size / 1024,
    )

    return ConversionResult(
        obj_path=obj_path,
        file_size_bytes=file_size,
        vertex_count=vertex_count,
        face_count=face_count,
        engine=engine,
    )
